spring.datasource.url=jdbc:mysql://localhost:3306/course_db
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.thymeleaf.cache=false
server.port=8080

# OAuth2 Google (fill in your credentials)
spring.security.oauth2.client.registration.google.client-id=821784060578-sb8vqel2joq6qkhn35a6v59m6g40pv41.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
